apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud
  namespace: mc-b
  description: Das Projekt LernCloud fasst immer wieder verwendete Scripts in einem
    Projekt zusammen und vermindert Copy & Paste.
  tags:
  - kubernetes
  - cloud-native
  - infrastructure-as-code
  - terraform
  - education
  links:
  - url: https://github.com/mc-b/lerncloud
    title: Repository
    icon: github
  annotations:
    github.com/project-slug: mc-b/lerncloud
    backstage.io/source-location: url:https://github.com/mc-b/lerncloud
    # backstage.io/techdocs-ref: url:https://github.com/mc-b/lerncloud
spec:
  type: infrastructure
  lifecycle: production
  owner: group:mc-b/mc-b
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Installiert die Grundtools um Backstage.io zu starten
  namespace: mc-b
spec:
  type: script
  lifecycle: experimental
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cert-manager
  description: Cert-Manager
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: containers
  description: Container-Tools wie podman, scopeo
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docker
  description: Docker 
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frpc
  description: Fast Reverse Proxy Client
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frps
  description: Fast Reverse Proxy Server
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: intro
  description: Erstellt die Intro Seiten
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: istio
  description: Istio
  namespace: mc-b
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: istio-patch
  description: Vermindert den Memory Verbrauch von istio
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: istio-zipkin
  description: Istio mit Zipkin
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jupyter-libraries
  description: Math Libraries zu den Jupyter Notebooks
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jupyter-notebook
  description: Jupyter Notebooks Umgebung
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k3s
  description: K3s
  namespace: mc-b
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8saddons
  namespace: mc-b
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8sbase
  namespace: mc-b
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8sjoin
  namespace: mc-b
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8smaster
  namespace: mc-b
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8stools
  description: Zusatztools zu Kubernetes wie k9s, stern, etc.
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8swebui
  namespace: mc-b
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kind-frp
  description: Kind im Zusammenspiel mit frp
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: knative
  description: K-native
  namespace: mc-b
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: knative-istio
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: knative-kafka
  namespace: mc-b
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: knative-patch
  description: Vermindert den Memory Verbrauch von K-native
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kubevirt
  description: KubeVirt
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kvm
  namespace: mc-b
spec:
  type: script
  lifecycle: experimental
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: longhorn
  description: Longhorn, verteiltes Dateisystem
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microk8s
  description: microk8s
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microk8saddons
  description: microk8s Add-on wie Dashboard und Metrics
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: nfsclient
  description: Stellt eine NFS Verbindung zum Rackserver her 
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nfsshare
  description: Stellt einen NFS Share /data zur Verfügung
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: podman
  namespace: mc-b
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: repository
  description: Ruft mit User ubuntu ein Installationsscript auf
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: share
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storage
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storage-patch
  description: Deaktiviert multipath und aktiviert iscsi für lohnhorn
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vault
  description: Vault von HashiCorp
  namespace: mc-b
spec:
  type: script
  lifecycle: experimental
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vpn
  description: Installiert und Konfiguriert WireGuard
  namespace: mc-b
spec:
  type: script
  lifecycle: production
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wake-on-lan
  description: Aktiviert Wake-On-LAN
  namespace: mc-b
spec:
  type: script
  lifecycle: experimental
  owner: mc-b
  partOf:
    - component:mc-b/lerncloud
  
