apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud
  namespace: mc-b
  tags:
  - cloud-native
  - education
  - infrastructure-as-code
  - kubernetes
  - lerncloud
  - lerngns3
  - lernmaas
  - terraform
  description: Das Projekt LernCloud fasst immer wieder verwendete Scripts in einem
    Projekt zusammen und vermindert Copy & Paste.
  links:
  - url: https://github.com/mc-b/lerncloud
    title: Repository
    icon: github
  annotations:
    github.com/project-slug: mc-b/lerncloud
    backstage.io/source-location: url:https://github.com/mc-b/lerncloud
    # backstage.io/techdocs-ref: url:https://github.com/mc-b/lerncloud
spec:
  type: infrastructure
  lifecycle: production
  owner: group:mc-b/mc-b
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-backstage
  description: Installiert die Grundtools um Backstage.io zu starten
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: experimental
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-cert-manager
  description: Cert-Manager
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-containers
  description: Container-Tools wie podman, scopeo
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-docker
  description: Docker 
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-frpc
  description: Fast Reverse Proxy Client
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-frps
  description: Fast Reverse Proxy Server
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-intro
  description: Erstellt die Intro Seiten
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-istio
  description: Istio
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-istio-patch
  description: Vermindert den Memory Verbrauch von istio
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-istio-zipkin
  description: Istio mit Zipkin
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-jupyter-libraries
  description: Math Libraries zu den Jupyter Notebooks
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-jupyter-notebook
  description: Jupyter Notebooks Umgebung
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-k3s
  description: K3s
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-k8saddons
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-k8sbase
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-k8sjoin
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-k8smaster
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-k8stools
  description: Zusatztools zu Kubernetes wie k9s, stern, etc.
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-k8swebui
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-kind-frp
  description: Kind im Zusammenspiel mit frp
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-knative
  description: K-native
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-knative-istio
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-knative-kafka
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-knative-patch
  description: Vermindert den Memory Verbrauch von K-native
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-kubevirt
  description: KubeVirt
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-kvm
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: experimental
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-longhorn
  description: Longhorn, verteiltes Dateisystem
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-microk8s
  description: microk8s
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-microk8saddons
  description: microk8s Add-on wie Dashboard und Metrics
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: lerncloud-nfsclient
  description: Stellt eine NFS Verbindung zum Rackserver her 
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-nfsshare
  description: Stellt einen NFS Share /data zur Verfügung
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-podman
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: deprecated
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-repository
  description: Ruft mit User ubuntu ein Installationsscript auf
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-share
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-storage
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-storage-patch
  description: Deaktiviert multipath und aktiviert iscsi für lohnhorn
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-vault
  description: Vault von HashiCorp
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: experimental
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-vpn
  description: Installiert und Konfiguriert WireGuard
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: production
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lerncloud-wake-on-lan
  description: Aktiviert Wake-On-LAN
  namespace: mc-b
  tags:
  - cloud-init
  - lerncloud
  - lerngns3
  - lernmaas
spec:
  type: script
  lifecycle: experimental
  owner: mc-b
  subcomponentOf: component:mc-b/lerncloud