apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cloud-init-generator
  title: Cloud Init Generator
  description: Gibt eine generierte cloud-init Datei als Copy & Paste aus
spec:
  owner: team-infra
  type: service

  parameters:
    - title: Optionen
      properties:
        install_docker:
          type: boolean
          title: Docker installieren
          default: false
        storage_mode:
          type: string
          title: Storage-Modus
          enum:
            - none
            - server
            - client
          default: none

  steps:
    - id: generate-cloud-init
      name: Generiere cloud-init Inhalt
      action: debug:log
      input:
        message: Rendering cloud-init.yaml

    - id: return-content
      name: Ausgabe erzeugen
      action: debug:log
      input:
        message: |
          #cloud-config
          users:
            - name: ubuntu
              sudo: ALL=(ALL) NOPASSWD:ALL
              shell: /bin/bash
          runcmd:
          {{ if parameters.install_docker }}
            - apt-get update
            - apt-get install -y docker.io
          {{ end }}
          {{ if parameters.storage_mode == "server" }}
            - apt-get install -y nfs-kernel-server
          {{ end }}
          {{ if parameters.storage_mode == "client" }}
            - apt-get install -y nfs-common
          {{ end }}

  output:
      text:
        - title: cloud-init.yaml
          content: |
            #cloud-config
            users:
              - name: ubuntu
                sudo: ALL=(ALL) NOPASSWD:ALL
                shell: /bin/bash
            runcmd:
            {{ if parameters.install_docker }}
              - apt-get update
              - apt-get install -y docker.io
            {{ end }}
            {{ if parameters.storage_mode == "server" }}
              - apt-get install -y nfs-kernel-server
            {{ end }}
            {{ if parameters.storage_mode == "client" }}
              - apt-get install -y nfs-common
            {{ end }}

